trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: DigitalOceanRegistry

steps:
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'pleyce.app'
      contents: 'docker-compose.yml'
      targetFolder: '/Workspace'
      readyTimeout: '20000'
  - task: SSH@0
    inputs:
      sshEndpoint: 'pleyce.app'
      runOptions: 'inline'
      inline: |
        echo Login to registry
        sudo docker login $(RegistryURL) -u $(RegistryUser) -p $(RegistryPassword)
        echo ------
        echo Open Workspace
        cd /Workspace
        sudo docker-compose pull && docker-compose up -d --remove-orphans
      failOnStdErr: false
      readyTimeout: '20000'