trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: DigitalOceanRegistry
- group: PleyceMessengerAPI

steps:
- script: |
    echo Replace variables on appsettings 
    cd MessengerApi.Webapi
    slackwebhook=$(SLACKWEBHOOK)
    awk -i inplace -v cuv1="__SLACKWEBHOOK__" -v cuv2="$slackwebhook" '{gsub(cuv1,cuv2); print;}' "appsettings.json"
    echo Build and push image to registry
    cd ..
    sh scripts/build-and-push-image-to-cr.sh $(RegistryURL) $(RegistryUser) $(RegistryPassword)