trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: DigitalOceanRegistry

steps:
- script: sh scripts/build-and-push-image-to-cr.sh $(RegistryURL) $(RegistryUser) $(RegistryPassword)
  displayName: 'Build and push image to registry'