trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: DigitalOceanRegistry
- group: PleyceMessengerAPI

steps:
- script: |
    echo Replace variables on appsettings 
    cd MessengerApi.Webapi
    slackwebhook=$(SLACKWEBHOOK)
    sed -i "s/__SLACKWEBHOOK__/$slackwebhook/" appsettings.json
    echo Build and push image to registry
    cd ..
    sh scripts/build-and-push-image-to-cr.sh $(RegistryURL) $(RegistryUser) $(RegistryPassword)