version: '3'

services:
    app:
      build:
        context: ..
        dockerfile: .devcontainer/Dockerfile
        args:
            # Update 'VARIANT' to pick a .NET Core version: 2.1, 3.1, 5.0
            VARIANT: 5.0
            INSTALL_NODE: "false"
            NODE_VERSION": "lts/*"
            INSTALL_AZURE_CLI: "false"

      volumes:
        - ..:/workspace:cached

      # Overrides default command so things don't shut down after the process ends.
      command: sleep infinity